stages:
  - test_and_codequality
  - coverage_and_mutation
  - docker_build
  - deploy_azure
  - deploy_aws

variables:
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

code_quality:
  stage: test_and_codequality
  image: python:3.11-slim
  before_script:
    - pip install pylint
  script:
    - pylint --rcfile=.pylintrc $(find . -name "*.py" | grep -v "^./tests") --fail-under=3.4 | tee pylint_report.txt | tail -n 4
  artifacts:
    paths:
      - pylint_report.txt
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "push"'

tests:
  stage: test_and_codequality
  image: python:3.11-slim
  before_script:
    - pip install pytest
  script:
    - pytest --ignore=kano-core --maxfail=1 --disable-warnings --junitxml=test-report.xml
  artifacts:
    paths:
      - test-report.xml
    reports:
      junit: test-report.xml
    expire_in: 1 week
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "push"'

test_coverage:
  stage: coverage_and_mutation
  image: python:3.11-slim
  before_script:
    - pip install pytest-cov pytest
  script:
    - pytest --ignore=kano-core --cov=. --cov-report=html --cov-report=term
  artifacts:
    paths:
      - htmlcov/
    expire_in: 1 week
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "push"'

docker_build:
  stage: docker_build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME
  only:
    - main

deploy_aws:
  stage: deploy_aws
  image: amazon/aws-cli
  variables:
    ECS_CLUSTER_NAME: "your-ecs-cluster-name"
    ECS_SERVICE_NAME: "your-ecs-service-name"
    AWS_DEFAULT_REGION: "us-east-1"
  script:
    - echo "Deploying to AWS ECS..."
    - sed -i "s/__DOCKER_IMAGE_NAME__/$DOCKER_IMAGE_NAME/g" task-definition.json
    - aws ecs register-task-definition --cli-input-json file://task-definition.json
    - aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --task-definition my-app
  only:
    - main

deploy_azure:
  stage: deploy_azure
  image: mcr.microsoft.com/azure-cli
  variables:
    AZURE_RESOURCE_GROUP: "your-resource-group"
    AZURE_APP_NAME: "your-app-name"
  script:
    - echo "Deploying to Azure App Service..."
    - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
    - az webapp config container set --name $AZURE_APP_NAME --resource-group $AZURE_RESOURCE_GROUP --docker-custom-image-name $DOCKER_IMAGE_NAME --docker-registry-server-user $CI_REGISTRY_USER --docker-registry-server-password $CI_REGISTRY_PASSWORD
  only:
    - main
